# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: table.proto for package ''

require './grpc'
require './table_pb'

module TableProductProvider
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'TableProductProvider'

    rpc :GetTableProduct, Filter, TableProduct
  end

  Stub = Service.rpc_stub_class
end
