# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Filter" do
    optional :id1, :string, 1
    optional :id2, :string, 2
    optional :dbId, :string, 3
  end
  add_message "TableProduct" do
    repeated :rows, :message, 1, "Row"
  end
  add_message "Row" do
    repeated :cells, :message, 1, "Cell"
  end
  add_message "Cell" do
    optional :value, :bytes, 1
    optional :colData, :message, 2, "ColumnData"
  end
  add_message "ColumnData" do
    optional :name, :string, 1
    optional :datatype, :string, 2
  end
end

Filter = Google::Protobuf::DescriptorPool.generated_pool.lookup("Filter").msgclass
TableProduct = Google::Protobuf::DescriptorPool.generated_pool.lookup("TableProduct").msgclass
Row = Google::Protobuf::DescriptorPool.generated_pool.lookup("Row").msgclass
Cell = Google::Protobuf::DescriptorPool.generated_pool.lookup("Cell").msgclass
ColumnData = Google::Protobuf::DescriptorPool.generated_pool.lookup("ColumnData").msgclass
