// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TableProductProviderClient is the client API for TableProductProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableProductProviderClient interface {
	GetTableProduct(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*TableProduct, error)
}

type tableProductProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewTableProductProviderClient(cc grpc.ClientConnInterface) TableProductProviderClient {
	return &tableProductProviderClient{cc}
}

func (c *tableProductProviderClient) GetTableProduct(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*TableProduct, error) {
	out := new(TableProduct)
	err := c.cc.Invoke(ctx, "/TableProductProvider/GetTableProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableProductProviderServer is the server API for TableProductProvider service.
// All implementations must embed UnimplementedTableProductProviderServer
// for forward compatibility
type TableProductProviderServer interface {
	GetTableProduct(context.Context, *Filter) (*TableProduct, error)
	mustEmbedUnimplementedTableProductProviderServer()
}

// UnimplementedTableProductProviderServer must be embedded to have forward compatible implementations.
type UnimplementedTableProductProviderServer struct {
}

func (UnimplementedTableProductProviderServer) GetTableProduct(context.Context, *Filter) (*TableProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableProduct not implemented")
}
func (UnimplementedTableProductProviderServer) mustEmbedUnimplementedTableProductProviderServer() {}

// UnsafeTableProductProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableProductProviderServer will
// result in compilation errors.
type UnsafeTableProductProviderServer interface {
	mustEmbedUnimplementedTableProductProviderServer()
}

func RegisterTableProductProviderServer(s grpc.ServiceRegistrar, srv TableProductProviderServer) {
	s.RegisterService(&TableProductProvider_ServiceDesc, srv)
}

func _TableProductProvider_GetTableProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableProductProviderServer).GetTableProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TableProductProvider/GetTableProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableProductProviderServer).GetTableProduct(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

// TableProductProvider_ServiceDesc is the grpc.ServiceDesc for TableProductProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableProductProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TableProductProvider",
	HandlerType: (*TableProductProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTableProduct",
			Handler:    _TableProductProvider_GetTableProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "table.proto",
}
